// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuZTTEPCBC0tZNKXhl8oRiXtDdbmBgq7Y',
    appId: '1:552120996167:web:22ee281f0346651285bc62',
    messagingSenderId: '552120996167',
    projectId: 'chatify-f7436',
    authDomain: 'chatify-f7436.firebaseapp.com',
    storageBucket: 'chatify-f7436.firebasestorage.app',
    measurementId: 'G-0N9CLF8QP3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuZTTEPCBC0tZNKXhl8oRiXtDdbmBgq7Y',
    appId: '1:552120996167:web:d23eef9633778f3c85bc62',
    messagingSenderId: '552120996167',
    projectId: 'chatify-f7436',
    authDomain: 'chatify-f7436.firebaseapp.com',
    storageBucket: 'chatify-f7436.firebasestorage.app',
    measurementId: 'G-0QDQG3H0GW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPJOm115NwgZLZO924oDg0TOwhPUQWGgQ',
    appId: '1:552120996167:ios:cadcd1f36f533dfc85bc62',
    messagingSenderId: '552120996167',
    projectId: 'chatify-f7436',
    storageBucket: 'chatify-f7436.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPJOm115NwgZLZO924oDg0TOwhPUQWGgQ',
    appId: '1:552120996167:ios:cadcd1f36f533dfc85bc62',
    messagingSenderId: '552120996167',
    projectId: 'chatify-f7436',
    storageBucket: 'chatify-f7436.firebasestorage.app',
    iosBundleId: 'com.example.chatifyApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI0o_kVZJJQSeEMoEhJ2djFM8Z_9Io0dM',
    appId: '1:552120996167:android:8bc62dfa45153f7b85bc62',
    messagingSenderId: '552120996167',
    projectId: 'chatify-f7436',
    storageBucket: 'chatify-f7436.firebasestorage.app',
  );

}